---
- name: Create a {{ application_name }} virtual server
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: root
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml

  roles:
    - base
    - java
    - youtube-dl
    - nginx
    - instamovie